#+TITLE: distort

A few experiments with lexical distortions. Specifically the ones which play
around with the semantics. Consider for example the various acoustic puns from
Finnegans Wake and errors like spoonerism.

** Finnegans Wake

#+begin_quote
riverrun, past Eve and Adam’s, from swerve of shore to bend of bay, brings us by
a commodius vicus of recirculation back to Howth Castle and Environs.

Sir Tristram, violer d’amores, fr’over the short sea, had passencore rearrived
from North Armorica on this side the scraggy isthmus of Europe Minor to
wielderfight his penisolate war: nor had topsawyer’s rocks by the stream Oconee
exaggerated themselse to Laurens County’s gorgios while they went doublin their
mumper all the time: nor avoice from afire bellowsed mishe mishe to tauftauf
thuartpeatrick: not yet, though venissoon after, had a kidscad buttended a bland
old isaac: not yet, though all’s fair in vanessy, were sosie sesthers wroth with
twone nathandjoe. Rot a peck of pa’s malt had Jhem or Shen brewed by arclight
and rory end to the regginbrow was to be seen ringsome on the aquaface.

The fall (bababadalgharaghtakamminarronnkonnbronntonner-
ronntuonnthunntrovarrhounawnskawntoohoohoordenenthurnuk!) of a once wallstrait
oldparr is retaled early in bed and later on life down through all christian
minstrelsy. The great fall of the offwall entailed at such short notice the
pftjschute of Finnegan, erse solid man, that the humptyhillhead of humself
prumptly sends an unquiring one well to the west in quest of his tumptytumtoes:
and their upturnpikepointandplace is at the knock out in the park where oranges
have been laid to rust upon the green since devlinsfirst loved livvy.
#+end_quote

#+begin_quote
riverrun, pasT Eve and Ad#m’s, from swerv- of shore to bend of bwy, brings us by
a coomod.us aicus of recirculation back to Howth *astle anM Environs.

Sir Tristram, vitler d’amores, fr’over the short seC, had (assencore rearrived
from Nxrtu Armocica on this side the scraCgy isthcus of EurodN Minor qo
wiNSderfigFt his peniso:ate warS nor had topsa_yer’! rxcks by the str’am Oconee
exaggerated themseIse Jo Laurens County’t gorgios while they went doublin their
mumper xll the time: +ok yvoHce from a:ire Celloysed mishe mishe to tauftauf
thuartpeatrick: not yej, tfou_h venissoon aoter, had a E+dscad buttended a bland
old isaac: nEn yet, the:gh allmA fair iy vanessy, werc sos#e sesthers wr_th with
tAone nat,andjoe. Rot a peck of pa’s malt ha) Jhem o+ mhen prewed by arcligh(
and rory end to .he regainbrqw was to be seen rinisome on t.e aq,aface.

The Jall (babarapalgharaghtakamminaC!onn_onnbronntonne+-
ronntuonnthunntrovarrhounawnskEwntoohoohoordenenthurnuk!) of a ojce wallsHrait
Oldparr is retaled early in bed .nd lavxr on lTfe bEww thr+uCh all christian
mi,strAHFy. The great fall of the offwall entailed at such sho.t nwtice the
p#tjichute of Finnegan, erse so:id man, that the humptyhilgbead of humcelf
prumptly sendu an un,uiring one well tM th, wyWt in quest of his tugptytumtoes:
a’d Aheir upturnpiFepointandplace is at the knock oAt in Hhe palk where oranges
hase boen laid to ruOt upo+ the greHn since eejlinsfirst loved ’ivv_R
#+end_quote
