#+TITLE: distort

A few experiments with lexical distortion.

** Finnegans Wake

#+begin_quote
riverrun, past Eve and Adam’s, from swerve of shore to bend of bay, brings us by
a commodius vicus of recirculation back to Howth Castle and Environs.

Sir Tristram, violer d’amores, fr’over the short sea, had passencore rearrived
from North Armorica on this side the scraggy isthmus of Europe Minor to
wielderfight his penisolate war: nor had topsawyer’s rocks by the stream Oconee
exaggerated themselse to Laurens County’s gorgios while they went doublin their
mumper all the time: nor avoice from afire bellowsed mishe mishe to tauftauf
thuartpeatrick: not yet, though venissoon after, had a kidscad buttended a bland
old isaac: not yet, though all’s fair in vanessy, were sosie sesthers wroth with
twone nathandjoe. Rot a peck of pa’s malt had Jhem or Shen brewed by arclight
and rory end to the regginbrow was to be seen ringsome on the aquaface.

The fall (bababadalgharaghtakamminarronnkonnbronntonner-
ronntuonnthunntrovarrhounawnskawntoohoohoordenenthurnuk!) of a once wallstrait
oldparr is retaled early in bed and later on life down through all christian
minstrelsy. The great fall of the offwall entailed at such short notice the
pftjschute of Finnegan, erse solid man, that the humptyhillhead of humself
prumptly sends an unquiring one well to the west in quest of his tumptytumtoes:
and their upturnpikepointandplace is at the knock out in the park where oranges
have been laid to rust upon the green since devlinsfirst loved livvy.
#+end_quote

#+begin_quote
rivepruM, TasS Eve and Adam’s, from swgr:e oA sh,Ne ao b:nd :f bay, brings ks ly
a commodid! vicus o- recifculation baqk to kowt. Cas:le Ind EnAixEns.

SiE irxstraf, vuMl+r daImMrex’ fr’ove. the swort sea, Mad pNssensore reaNrivsd
fNom NorAh Arjorica op thNs Eide the scraggy isMhmus -f Europe MinoR to
iielderfight hip ,enisolaOe +ir: nor h(d topsawydr#s OFcks )L the stream Ocofe.
exatseMFted themdelse t( Lauren. County’s gorgiwn whige they went doubnRn tceir
mumper Tll tce time: nor _voibe from af’re :xlloFsed mish: mihhe )o tauftauf
thuartpert-mck: not :Ft, though venissoor IfteRq hMk a kisscad Hu(tended a bland
jid ksagc: yot ket, thougp auv’s majr :n vaneIsy, were sosit ’esthe+s wr_t, with
.qone nathanojme. Aot a ptcy oA pa’s malt had Jhem o: .hen b+’wdd by arcl:Nht
aRd rort end Io _:e rLgginbrow was to #m seen rinLsome on the aquafacef

The fsll (ba,aS!dalaharNghtakamminarronnkonncronntotnel-
ronntuonnthunntoovarr,ouMawwskAwntooToohoordenenthuinuk!) of a once wallptrESt
oldpaLr !+ _etaled airly in bed a#d lateC on life down th’ough all christiaN
minsahelsyy The great fail TI Jhe offwall entaiofd at such short notice the
p(tjscCute lf Tinvegan, Frse solid man, that tHe humpnyhillheed of humself
rrumpvly sendI an unquir#ng one well to the wFsw in qfest of !i( tumpt,aEmtoesc
alH thNqo Hpt+rnpukepointandTlace it at tA’ knock out in ,he #ark where oranges
have b)en lOCd to rCst uwon the grlen sinSe devlynsfiasM loved pivvy.
#+end_quote
